### ISSUE TITLE
Private topic 

### ISSUE THREAD

**Issue by clin9** [aws-samples/aws-iot-chat-example#12]
Hi,

I follow this repository for a long time. It is really great to demo the AWS Iot. But there is a question after understanding and researching AWS Iot and this repository. How could you provide the private topic for specific user ? In my understanding, aws iot provides the Cognito identity role for access the topic but everyone who is authorized by  Cognito identity pool are able to access same topic that we cannot distinguish only who are able to access it. it's means the topic will expose to identity pool user. So it cannot be private.  Am I right?

Thanks.

**Comment by VishnupriyaVallinayagam** [comment]
It seems we can restrict access to user's topics and it is been mentioned in documentation like "To prevent users from publishing to other user's topics, the AWS Lambda function AttachPublicPublish creates a dynamic IoT policy that allows only that one identity to publish messages to their unique topic."

Further, to restrict topic access in aws iot, follow this link [https://medium.com/@florianherrengt/restrict-topic-access-in-aws-iot-d35b58442399](url)

**Comment by clin9** [comment]
Thank you for replying.

Yeah, we are able to "prevent users from publishing to other user's topic", but how about preventing users from subscribing other user's topic? Like userA only can subscribes topicA and userB only can subscrible topicB but userA cannot subscrible topicB. Since Cogntio Identity use role as to get accessId and accesssKey, it seems all users will have the same permission to access topic. Is is possible to restrict subscribe the user's topic with different user id or group or something like that?

**Comment by VishnupriyaVallinayagam** [comment]
For the same you have another AWS Lambda Function 'AttachPublicSubscribe' in this application.

And generally (I guess), when we restrict access to a topic using IoT Policy, we cannot publish and receive messages from the topic.

**Comment by Nosajool** [comment]
Yes, you can create policies for restricting permissions on subscribe actions. See https://docs.aws.amazon.com/iot/latest/developerguide/iot-policy-actions.html for more detail.

This demo application creates an "allow everything" under the topic filter `:topicfilter/room/public/*` policy.

```yaml
        PolicyName: IotChatPublicSubscribePolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "iot:Subscribe"
              Resource:
                {
                  "Fn::Join":
                    [
                      "",
                      [
                        "arn:aws:iot:",
                        { "Ref": "AWS::Region" },
                        ":",
                        { "Ref": "AWS::AccountId" },
                        ":topicfilter/room/public/*",
                      ],
                    ],
                }
```

But you can definitely use more restrictive topic filters to prevent certain identities from subscribing to certain topics.
