### ISSUE TITLE
connection error: MOZILLA_PKIX_ERROR_ADDITIONAL_POLICY_CONSTRAINT_FAILED

### ISSUE THREAD

**Issue by AshleyMcVeigh** [aws-samples/aws-iot-chat-example#14]
It appears as though browsers (specifically Firefox 64) changed something certificate related and now you can't connect to IoT from a browser. the hosted example application no longer works in these newer browsers.

**update**: The problem is that AWS is issuing their own certificates and your browser doesn't think they're legit, I got around the issue by putting my AWS IoT endpoint behind a cloudflare rule of one of my domains (I don't know the specifics as it wasn't me who actually did it), but if anyone is having this issue, that's an option.

**Comment by AshleyMcVeigh** [comment]
browser: Firefox 64

When I open the demo application (the hosted one linked in the readme) the connections to the IOT service fail with a "security error"

this URL specifically:
```
https://aa62svu223r8t.iot.us-west-2.amazonaws.com/mqtt?...
```

the specific error shown on the "security" tab in Firefox dev tools when I click on the request is 

```
MOZILLA_PKIX_ERROR_ADDITIONAL_POLICY_CONSTRAINT_FAILED
```

I should also note in my application that had this same issue it was also failing in latest chrome and safari.

**Comment by leogonzalez** [comment]
Hi - this blog post helped me solve it: https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/

So Amazon added a `-ats` at the iot endpoint to provide new certificates out of the box. I added this to my IOT endpoint and now the application is working out of the box again.

**Comment by leogonzalez** [comment]
So @AshleyMcVeigh maybe try to alter your endpoint to `https://aa62svu223r8t-ats.iot.us-west-2.amazonaws.com` and maybe it will work

**Comment by Nosajool** [comment]
Deployed updated client that connects to the `-ats` endpoint. This should be fixed now.
