### ISSUE TITLE
Cert authority error

### ISSUE THREAD

**Issue by dtweedle** [aws-samples/aws-iot-chat-example#16]
Potentially related to issue #14 error but in chrome.

failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

**Comment by leogonzalez** [comment]
Hi - this blog post helped me solve it: https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/

So Amazon added a `-ats` at the endpoint to provide new certificates out of the box. I added this to my IOT endpoint and now the application is working out of the box again.

**Comment by Nosajool** [comment]
Yes, recommended to now use the `ats` endpoint. Thank you Leo for the pull request.
