### ISSUE TITLE
Chat App IoT Topic Explanation

### ISSUE THREAD

**Issue by leogonzalez** [aws-samples/aws-iot-chat-example#17]
Hi, 

on the Authentication Guide there's a missing link on this sentence "Also see Chat App IoT Topic Explanation for an explanation of the topic space used for this application."

https://github.com/aws-samples/aws-iot-chat-example/blob/master/docs/iot_topics.md

Does this explanation exist? 

Thank you

**Comment by Nosajool** [comment]
Hi Leo, thanks for pointing this out. This explanation has been moved into the README and I have now updated the broken link.
