### ISSUE TITLE
__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function

### ISSUE THREAD

**Issue by yugushihuang** [aws-samples/aws-iot-chat-example#19]
When I try to login user from localhost:3000/login I get the error of ->

__WEBPACK_IMPORTED_MODULE_0_aws_sdk_global__.util.crypto.lib.randomBytes is not a function

Anybody have same issue and resolved?

**Comment by kevinyea** [comment]
You probably fixed it but for anyone else, long history here: https://github.com/amazon-archives/amazon-cognito-identity-js/issues/646

The workaround "As a temporary fix, we have locked down the AWS SDK version number to v2.177.0. Pulling in the latest version of this package should work." From my package.json:
` "dependencies": {
    "amazon-cognito-identity-js": "1.19.0",
    "aws-iot-device-sdk": "2.1.0",
    "aws-sdk": "2.177.0",
    "crypto-js": "^3.1.9-1",
    "history": "^4.9.0",
    "loglevel": "^1.6.3",
`

**Comment by Nosajool** [comment]
`package.json` has been updated. Feel free to re-open if you are still seeing issues.
