### ISSUE TITLE
avoid someone from subscribing to a topic they are not supposed to ? 

### ISSUE THREAD

**Issue by maheshgawali** [aws-samples/aws-iot-chat-example#2]
First off, kudos to the awesom end-to-end information you have put together. Its been really helpful.

**Couple of Questions:**

1. how do we avoid someone from subscribing to a topic they are not supposed to ? 

> client_issues_subscription_to_chatroom1 -> server_checks_access_level -> unauthorized -> dont_allow_subscription_to_chatroom1

> is policies the only way to handle such cases ?

2. What if Users can create multiple **private** rooms and add different users in them, should we be dynamically updating policies in such cases ?

3. Also is it possible to unsubscribe someone from server ? _say in case an admin removes someone from a chatroom_

**Comment by Nosajool** [comment]
1. You can create a more restrictive policy using a tighter topic filter. See [iot-policy-actions docs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policy-actions.html) and [iot-action-resources docs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-action-resources.html). This demo uses the filter:`:topicfilter/room/public/*`
2. That can be accomplished using dynamic IoT policies.
3. Yes, you could revoke policies or add an [explicit deny policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#AccessPolicyLanguage_Interplay). Just note that there is a delay for these policies to propagate to AWS IoT so it would not take effect immediately.
