### ISSUE TITLE
Running in Windows get error because of ./script/attachConfirmUserTrigger.sh

### ISSUE THREAD

**Issue by pmenico** [aws-samples/aws-iot-chat-example#20]
When running this on Windows10 I get the following errors running the script:

Serverless: Running after:aws:deploy:finalize:cleanup command: "./scripts/attachConfirmUserTrigger.sh"
'.' is not recognized as an internal or external command,
operable program or batch file.

I looked at serverless.yml and it has the leading "." on the commands.
  hooks:
    after:aws:deploy:finalize:cleanup:
      - ./scripts/attachConfirmUserTrigger.sh
      - ./../client/scripts/setup.sh
    before:remove:remove:
      - ./scripts/detach_policies.sh

If I remove these "." ahead of these 3 scripts and rerun the whole "serverless deploy" will it mess up anything? Or is there a short cut to just run these remaining scripts?
Thank you

**Comment by JLee21** [comment]
> If I remove these "." ahead of these 3 scripts and rerun the whole "serverless deploy" will it mess up anything?

Yah, b/c severless won't be able to find those scripts anymore.

@pmenico I believe if you'd like to run shell scripts on Windows you can [enable Bash on Windows 10](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/) or install a unix-like CLI interface like Cygwin. Then you should be able to can run those scripts as is.

**Comment by Nosajool** [comment]
I'll add a note that this app has not been tested on Windows.
