### ISSUE TITLE
example not up to date, unable to follow, fsevents not installable and more

### ISSUE THREAD

**Issue by hdmt-hock** [aws-samples/aws-iot-chat-example#28]
MAC osx 10.14.5
nodejs 10.16.0
node-gyp 5.0.3 (report "Not ok" during install)
node-pre-gyp 0.12.0 (report "Not ok" during install)
npm 6.10.2

General request:
0. Could this example update the necessary informations and contents to reflect the changes in the current AWS setup?  It seems outdated.

problem face during followup on the instruction provided:
1. npm report too many vulnerabilities during install

2. since I am new to this, have been using "npm audit fix --force" to get the stuff going, I have no idea what to fix

3. fsevents@1.1.2 version number does not exist or not accessible, not installable, I manage to clone the fsevents@2.0.7 from github and install seperately.

4. at the time I am writing this issues, I am still in "Step 3:Run the frontend client" of the installation instruction "npm install".

5. Some warning appear, are they really warning?
npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.6.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/typescript-estree@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-eslint@10.0.1 requires a peer of eslint@>= 4.12.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@4.0.1 requires a peer of eslint@5.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@4.0.1 requires a peer of eslint-plugin-jsx-a11y@6.x but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.14.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev but none is installed. You must install peer dependencies yourself.

hopefully some positive information in the next days,

**Comment by hdmt-hock** [comment]
Update : 

reinstalling node js and follow the instruction again (with "sudo" admin right to all , skipping all the warning)

manage to start localhost:3000/register with the page to register.
but the default localhost:3000/login show the following on the page.

TypeError: Cannot read property 'render' of undefined
new n
node_modules/react-social-login/dist/social-login.js:4013
  4010 | function n(e) {
  4011 |   i(this, n);
  4012 |   var r = o(this, (n.__proto__ || Object.getPrototypeOf(n)).call(this, e));
> 4013 |   return r.isStateless = !t.prototype.render, r.state = {
       | ^  4014 |     isLoaded: !1,
  4015 |     isConnected: !1,
  4016 |     isFetching: !1

What did I miss?

**Comment by Nosajool** [comment]
Hi, I have updated the npm audit issues. Please re-open if you are still seeing these problems.
