### ISSUE TITLE
Rate limit on policy actions

### ISSUE THREAD

**Issue by Sergio-Mira** [aws-samples/aws-iot-chat-example#37]
There seems to be a small API limit on policy operations: https://docs.aws.amazon.com/general/latest/gr/iot-core.html#message-broker-limits

This means that only 15 policies can be added per second. Would the `attach policy` lambdas fail if ~3 users were to register simultaneously? (each user uses 4 policies actions and there is a rate limit of 15 per second)

**Comment by Sergio-Mira** [comment]
Could be doable I think with a Custom Authorizer that sets the right policies to the needed topics
https://docs.aws.amazon.com/iot/latest/developerguide/custom-authorizer.html

**Comment by Nosajool** [comment]
Yes, the Lambda APIs in this example are not reliable/resilient services. If building a production app, should use retries.

This is also an adjustable TPS limit that you can have AWS increase if needed.
