### ISSUE TITLE
Online Demo with certified error on connect to WSS:

### ISSUE THREAD

**Issue by rafaelargenta-picpay** [aws-samples/aws-iot-chat-example#48]
We cannot use the online demo.
We get stuck in the screen "Connectin" and in browser console we can see a error with the certifies and the wss: connection..

**Comment by Nosajool** [comment]
Ah, I see, the online demo client needs to use the `-ats` from https://github.com/aws-samples/aws-iot-chat-example/pull/18  

I will see if I can get access to deploy the updated code this week.

**Comment by rafaelargenta-picpay** [comment]
Thanks, we are waiting for!

**Comment by Nosajool** [comment]
Hi @rafaelargenta-picpay I have deployed the latest client code to the online demo at https://d2ab9cgiumpbb1.cloudfront.net/
