### ISSUE TITLE
SOLVED: Parsing error when using jq command

### ISSUE THREAD

**Issue by JLee21** [aws-samples/aws-iot-chat-example#9]
This issue is solved. I'm posting this to help others.

When launching the jq command you may have run into this imprecise error:

`parse error: Invalid numeric literal at line 1, column 7`

According to this jq [github issue](https://github.com/stedolan/jq/issues/501), this error comes from the following comment:

> Essentially, the logic is: is it an array? nope. is it an object? nope. (...) well, it must be a number. parse error on a number.

So what's going on here? Within your `.aws/credentials` or `.aws/config` options, change the output field to `json`. Now, jq will be able to correctly parse the JSON results from the aws cli commands. The root cause is that you must have had the output set to `text`.

**Comment by ramirez1968** [comment]
wow....@JLee21 you have no idea how amazing that solution is my friend!!! thank you!!!
